<a href="https://colab.research.google.com/github/HongSeongMo/Bigdata_Analysis_Professional/blob/main/241009.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import numpy as np
a = np.array([80,82,90,89])
b = np.array([[27,19,78],[99,22,35]])
c = np.array([[70,85,75],[45,89,67]])
print('-----concatenate----------')


-----concatenate----------


In [7]:
con1 = np.concatenate((a,[75,66,88]))
print(con1)

[80 82 90 89 75 66 88]


In [8]:
con2 = np.concatenate((b,c))
print(con2)

[[27 19 78]
 [99 22 35]
 [70 85 75]
 [45 89 67]]


In [9]:
con3 = np.concatenate((b,c),axis=0)
print(con3)

[[27 19 78]
 [99 22 35]
 [70 85 75]
 [45 89 67]]


In [10]:
con4 = np.concatenate((b,c),axis=1)
print(con4)

[[27 19 78 70 85 75]
 [99 22 35 45 89 67]]


In [11]:
stack1 = np.stack((b,c), axis=0)
print(stack1)

[[[27 19 78]
  [99 22 35]]

 [[70 85 75]
  [45 89 67]]]


In [12]:
stack2 = np.stack((b,c), axis=1)
print(stack2)

[[[27 19 78]
  [70 85 75]]

 [[99 22 35]
  [45 89 67]]]


In [14]:
appd1 = np.append(b,c)
print(appd1)

[27 19 78 99 22 35 70 85 75 45 89 67]


In [15]:
appd2 = np.append(b,c,axis=0)
print(appd2)

[[27 19 78]
 [99 22 35]
 [70 85 75]
 [45 89 67]]


In [16]:
appd3 = np.append(b,c,axis=1)
print(appd3)

[[27 19 78 70 85 75]
 [99 22 35 45 89 67]]


In [17]:
spt1 = np.split(appd3,2, axis=0)
print(spt1)

[array([[27, 19, 78, 70, 85, 75]]), array([[99, 22, 35, 45, 89, 67]])]


In [18]:
spt2 = np.split(appd3,2, axis=1)
print(spt2)

[array([[27, 19, 78],
       [99, 22, 35]]), array([[70, 85, 75],
       [45, 89, 67]])]


In [20]:
arr1 = spt2[0]
arr1

array([[27, 19, 78],
       [99, 22, 35]])

In [22]:
arr2 = spt2[1]
arr2

array([[70, 85, 75],
       [45, 89, 67]])

In [23]:
import numpy as np
a = np.arange(18).reshape(6,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [25]:
split1 = np.split(a,2, axis=0)
split1

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [26]:
split2 = np.split(a,3, axis=1)
split2

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [29]:
b = np.arange(10);b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
split3 = np.split(b,[2,5], axis=0)
split3

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [31]:
split4 = np.split(b,[3,6,9], axis=0)
split4

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([9])]

In [32]:
import numpy as np
import pandas as pd

a = np.array([1,27,19,35,34,22,55])
b = np.array([2,70,85,75,45,89,57])
c = np.array([3,80,80,90,80,87,88])

df1 = pd.DataFrame([a,b,c])
df1


0   1   2   3   4   5   6
0  1  27  19  35  34  22  55
1  2  70  85  75  45  89  57
2  3  80  80  90  80  87  88

In [34]:
df2 = pd.DataFrame([a,b,c], columns = ['id','math','eng','python','R','kor','bio'])
df2

id  math  eng  python   R  kor  bio
0   1    27   19      35  34   22   55
1   2    70   85      75  45   89   57
2   3    80   80      90  80   87   88

In [35]:
df2 = df2.set_index('id')
df2

math  eng  python   R  kor  bio
id                                 
1     27   19      35  34   22   55
2     70   85      75  45   89   57
3     80   80      90  80   87   88