<a href="https://colab.research.google.com/github/HongSeongMo/Bigdata_Analysis_Professional/blob/main/241008.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inst = input('소속입력:')
print(inst)

소속입력:고려대학교
고려대학교


In [ ]:
x = int(input('파이썬 점수: '))
y = int(input('C언어 점수: '))
print((x+y)/2)

파이썬 점수: 90
C언어 점수: 80
85.0


In [ ]:
inst = input('소속기관은 어디인가요:')
print('당신의 소속기관은', inst, '입니다.')

소속기관은 어디인가요:고려대학교
당신의 소속기관은 고려대학교 입니다.


In [ ]:
print('당신의 소속기관은 %s' % inst, '입니다.')

당신의 소속기관은 고려대학교 입니다.


In [ ]:
f'{x} + {y} = {x+y}'

'90 + 80 = 170'

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sale.csv', encoding='euc-kr', header=0, index_col=0)
pd.options.display.max_colwidth = 8
pd.options.display.max_columns = None
df.head()

총구매액    최대구매액     환불금액   주구매상품 주구매지점  내점일수  내점당구매건수   주말방문비율  구매주기
cust_id                                                                       
0        6828...  1126...  6860...      기타   강남점    19  3.89...  0.52...    17
1        2136000  2136000  3000...     스포츠   잠실점     2  1.50...  0.00...     1
2        3197000  1639000      NaN  남성 캐주얼   관악점     2  2.00...  0.00...     1
3        1607...  4935000      NaN      기타   광주점    18  2.44...  0.31...    16
4        2905...  2400...      NaN      보석  본  점     2  1.50...  0.00...    85

In [ ]:
df.isnull()

총구매액  최대구매액   환불금액  주구매상품  주구매지점   내점일수  내점당구매건수  주말방문비율   구매주기
cust_id                                                                  
0        False  False  False  False  False  False    False   False  False
1        False  False  False  False  False  False    False   False  False
2        False  False   True  False  False  False    False   False  False
3        False  False   True  False  False  False    False   False  False
4        False  False   True  False  False  False    False   False  False
...        ...    ...    ...    ...    ...    ...      ...     ...    ...
3495     False  False   True  False  False  False    False   False  False
3496     False  False  False  False  False  False    False   False  False
3497     False  False   True  False  False  False    False   False  False
3498     False  False   True  False  False  False    False   False  False
3499     False  False  False  False  False  False    False   False  False

[3500 rows x 9 columns]

In [ ]:
df.isnull().sum()

총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

In [ ]:
df.isna()

총구매액  최대구매액   환불금액  주구매상품  주구매지점   내점일수  내점당구매건수  주말방문비율   구매주기
cust_id                                                                  
0        False  False  False  False  False  False    False   False  False
1        False  False  False  False  False  False    False   False  False
2        False  False   True  False  False  False    False   False  False
3        False  False   True  False  False  False    False   False  False
4        False  False   True  False  False  False    False   False  False
...        ...    ...    ...    ...    ...    ...      ...     ...    ...
3495     False  False   True  False  False  False    False   False  False
3496     False  False  False  False  False  False    False   False  False
3497     False  False   True  False  False  False    False   False  False
3498     False  False   True  False  False  False    False   False  False
3499     False  False  False  False  False  False    False   False  False

[3500 rows x 9 columns]

In [ ]:
df.isna().sum()

총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

In [ ]:
dfnew = df[df['환불금액'].notnull()]
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1205 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     1205 non-null   int64  
 1   최대구매액    1205 non-null   int64  
 2   환불금액     1205 non-null   float64
 3   주구매상품    1205 non-null   object 
 4   주구매지점    1205 non-null   object 
 5   내점일수     1205 non-null   int64  
 6   내점당구매건수  1205 non-null   float64
 7   주말방문비율   1205 non-null   float64
 8   구매주기     1205 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 94.1+ KB


In [ ]:
dfnew.isnull().sum()

총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

In [ ]:
dfnew.shape

(1205, 9)

In [ ]:
len(df), len(dfnew)

(3500, 1205)

In [ ]:
import numpy as np

a = np.array([1,27,19,35,34,22,55])
b = np.array([2,70,85,75,45,89,57])
c = np.array([3,80,80,90,80,87,88])
df1 = pd.DataFrame([a,b,c])
df2 = pd.DataFrame([a,b,c], columns=['id','math','eng','python','R','kor','bio'])
df2 = df2.set_index(keys='id')
df1

0   1   2   3   4   5   6
0  1  27  19  35  34  22  55
1  2  70  85  75  45  89  57
2  3  80  80  90  80  87  88

In [ ]:
df2

math  eng  python   R  kor  bio
id                                 
1     27   19      35  34   22   55
2     70   85      75  45   89   57
3     80   80      90  80   87   88

In [ ]:
numpy1 = df2.values; print(numpy1)
numpy2 = df2.to_numpy(); print(numpy2)

[[27 19 35 34 22 55]
 [70 85 75 45 89 57]
 [80 80 90 80 87 88]]
[[27 19 35 34 22 55]
 [70 85 75 45 89 57]
 [80 80 90 80 87 88]]


In [ ]:
type(numpy1), type(numpy2)

(numpy.ndarray, numpy.ndarray)

In [ ]:
type(numpy2)

numpy.ndarray

In [ ]:
numpy2[0]

array([27, 19, 35, 34, 22, 55])

In [ ]:
numpy2[1]

array([70, 85, 75, 45, 89, 57])

In [ ]:
numpy2[2]

array([80, 80, 90, 80, 87, 88])

In [ ]:
numpy2[2,4]

87

In [ ]:
numpy2[1][4]

89

In [ ]:
numpy2[2][4]

87

In [ ]:
numpy2[1,4]

89

In [ ]:
 avg = df['환불금액'].mean()
 avg

24078215.991701245

In [ ]:
df1 = df.copy()
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3500 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   int64  
 1   최대구매액    3500 non-null   int64  
 2   환불금액     1205 non-null   float64
 3   주구매상품    3500 non-null   object 
 4   주구매지점    3500 non-null   object 
 5   내점일수     3500 non-null   int64  
 6   내점당구매건수  3500 non-null   float64
 7   주말방문비율   3500 non-null   float64
 8   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 273.4+ KB


In [ ]:
df1['환불금액'] = df1['환불금액'].fillna(avg)
df1.isnull().sum()

총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
dtype: int64

In [ ]:
df1['환불금액'].mean()

24078215.99170124

In [ ]:
min = df['환불금액'].min()
max = df['환불금액'].max()
min, max

(5600.0, 563753000.0)

In [ ]:
df2 = df.copy()
df2['환불금액'] = df2['환불금액'].fillna(min)
df2['환불금액'].mean()

8293457.791428572

In [ ]:
df3 = df.copy()
df3['환불금액'] = df3['환불금액'].fillna(max)
df3['환불금액'].mean()


377950681.5057143

In [ ]:
df.isna().sum()

총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/sale.csv', encoding='euc-kr', header=0, index_col=0)
pd.options.display.max_colwidth = 20
pd.options.display.max_columns = None
df.head()

총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
cust_id                                                                
0        68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1         2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2         3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3        16077620   4935000        NaN      기타   광주점    18  2.444444   
4        29050000  24000000        NaN      보석  본  점     2  1.500000   

           주말방문비율  구매주기  
cust_id                  
0        0.527027    17  
1        0.000000     1  
2        0.000000     1  
3        0.318182    16  
4        0.000000    85

In [ ]:
# df1 = df.groupby('주구매상품').mean()
# data1 = pd.DataFrame(df1['내점일수'])
# data1.head()
df.dtypes

총구매액         int64
최대구매액        int64
환불금액       float64
주구매상품       object
주구매지점       object
내점일수         int64
내점당구매건수    float64
주말방문비율     float64
구매주기         int64
dtype: object

In [ ]:
dfnew = df.groupby('주구매지점').sum()
data2 = pd.DataFrame(dfnew['총구매액'])
data2.head()

총구매액
주구매지점             
강남점    10151146180
관악점     4242305350
광주점    17531487810
노원점     6960693550
대구점      701926580

In [39]:
import numpy as np
list1 = [27,19,35,34,22,55]
list2 = [70,85,75,45,89,57]
list3 = [80,80,90,80,87,88]
a = np.array(list1)
a

array([27, 19, 35, 34, 22, 55])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.shape

(6,)

In [42]:
len(a)

6

In [43]:
b = np.array([list1,list2])
b

array([[27, 19, 35, 34, 22, 55],
       [70, 85, 75, 45, 89, 57]])

In [44]:
b.shape

(2, 6)

In [45]:
len(b)

2

In [46]:
b[1,2]

75

In [47]:
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
type(c)

numpy.ndarray

In [49]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
e = np.full((3,3),10)
e

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [51]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
g = np.array(range(0,10,2))
g

array([0, 2, 4, 6, 8])

In [53]:
k = np.array(range(20)).reshape((5,4))
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [54]:
m = np.array(range(21)).reshape((-1,7))
m

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [55]:
n = np.array(range(21)).reshape((7,-1))
n

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [66]:
q = np.linspace(0,10, num=6)
q

array([ 0.,  2.,  4.,  6.,  8., 10.])

range(1, 46, 6)
