<a href="https://colab.research.google.com/github/HongSeongMo/Bigdata_Analysis_Professional/blob/main/241009.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import numpy as np
a = np.array([80,82,90,89])
b = np.array([[27,19,78],[99,22,35]])
c = np.array([[70,85,75],[45,89,67]])
print('-----concatenate----------')


-----concatenate----------


In [7]:
con1 = np.concatenate((a,[75,66,88]))
print(con1)

[80 82 90 89 75 66 88]


In [8]:
con2 = np.concatenate((b,c))
print(con2)

[[27 19 78]
 [99 22 35]
 [70 85 75]
 [45 89 67]]


In [9]:
con3 = np.concatenate((b,c),axis=0)
print(con3)

[[27 19 78]
 [99 22 35]
 [70 85 75]
 [45 89 67]]


In [10]:
con4 = np.concatenate((b,c),axis=1)
print(con4)

[[27 19 78 70 85 75]
 [99 22 35 45 89 67]]


In [11]:
stack1 = np.stack((b,c), axis=0)
print(stack1)

[[[27 19 78]
  [99 22 35]]

 [[70 85 75]
  [45 89 67]]]


In [12]:
stack2 = np.stack((b,c), axis=1)
print(stack2)

[[[27 19 78]
  [70 85 75]]

 [[99 22 35]
  [45 89 67]]]


In [14]:
appd1 = np.append(b,c)
print(appd1)

[27 19 78 99 22 35 70 85 75 45 89 67]


In [15]:
appd2 = np.append(b,c,axis=0)
print(appd2)

[[27 19 78]
 [99 22 35]
 [70 85 75]
 [45 89 67]]


In [16]:
appd3 = np.append(b,c,axis=1)
print(appd3)

[[27 19 78 70 85 75]
 [99 22 35 45 89 67]]


In [17]:
spt1 = np.split(appd3,2, axis=0)
print(spt1)

[array([[27, 19, 78, 70, 85, 75]]), array([[99, 22, 35, 45, 89, 67]])]


In [18]:
spt2 = np.split(appd3,2, axis=1)
print(spt2)

[array([[27, 19, 78],
       [99, 22, 35]]), array([[70, 85, 75],
       [45, 89, 67]])]


In [20]:
arr1 = spt2[0]
arr1

array([[27, 19, 78],
       [99, 22, 35]])

In [22]:
arr2 = spt2[1]
arr2

array([[70, 85, 75],
       [45, 89, 67]])